apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web # The Pods get this label
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80